name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build Kongruencia/Kongruencia.Server --file Kongruencia/Kongruencia.Server/Dockerfile --tag kongruenzia.server:$(date +%s)
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: tknapp/tknapp/kongruenzia.server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Kongruencia/Kongruencia.Server/Dockerfile
        context: Kongruencia/Kongruencia.Server
        
