name: Docker Image CI

on:
  push:
    branches:
    - feature/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get branch name
      uses: nelonoel/branch-name@v1
    - name: Build the Docker image
      run: docker build Kongruencia/Kongruencia.Server --file Kongruencia/Kongruencia.Server/Dockerfile --tag kongruenzia.server:${BRANCH_NAME}$(date +%s)
